var annotated_dup =
[
    [ "angles", "namespaceangles.html", [
      [ "Interval", "structangles_1_1Interval.html", "structangles_1_1Interval" ]
    ] ],
    [ "AlternatingDualRayOfLightObject", "classAlternatingDualRayOfLightObject.html", "classAlternatingDualRayOfLightObject" ],
    [ "ArenaGeometry", "classArenaGeometry.html", "classArenaGeometry" ],
    [ "BoundingBox", "structBoundingBox.html", "structBoundingBox" ],
    [ "BoundingDisk", "structBoundingDisk.html", "structBoundingDisk" ],
    [ "Candidate", "structCandidate.html", "structCandidate" ],
    [ "color_t", "structcolor__t.html", "structcolor__t" ],
    [ "Configuration", "classConfiguration.html", "classConfiguration" ],
    [ "ConstMsgSuccessRate", "classConstMsgSuccessRate.html", "classConstMsgSuccessRate" ],
    [ "DataLogger", "classDataLogger.html", "classDataLogger" ],
    [ "DiskGeometry", "classDiskGeometry.html", "classDiskGeometry" ],
    [ "DynamicMsgSuccessRate", "classDynamicMsgSuccessRate.html", "classDynamicMsgSuccessRate" ],
    [ "emitting_power_list_t", "unionemitting__power__list__t.html", "unionemitting__power__list__t" ],
    [ "GlobalGeometry", "classGlobalGeometry.html", "classGlobalGeometry" ],
    [ "GridCell", "structGridCell.html", "structGridCell" ],
    [ "GridCellHash", "structGridCellHash.html", "structGridCellHash" ],
    [ "Interval", "structInterval.html", "structInterval" ],
    [ "LightLevelMap", "classLightLevelMap.html", "classLightLevelMap" ],
    [ "MembraneObject", "classMembraneObject.html", "classMembraneObject" ],
    [ "message_header_t", "structmessage__header__t.html", "structmessage__header__t" ],
    [ "message_short_header_t", "structmessage__short__header__t.html", "structmessage__short__header__t" ],
    [ "message_t", "structmessage__t.html", "structmessage__t" ],
    [ "MsgSuccessRate", "classMsgSuccessRate.html", "classMsgSuccessRate" ],
    [ "Object", "classObject.html", "classObject" ],
    [ "ObjectGeometry", "classObjectGeometry.html", "classObjectGeometry" ],
    [ "PassiveObject", "classPassiveObject.html", "classPassiveObject" ],
    [ "PhysicalObject", "classPhysicalObject.html", "classPhysicalObject" ],
    [ "PogobjectObject", "classPogobjectObject.html", "classPogobjectObject" ],
    [ "PogobotObject", "classPogobotObject.html", "classPogobotObject" ],
    [ "Pogowall", "classPogowall.html", "classPogowall" ],
    [ "RectangleGeometry", "classRectangleGeometry.html", "classRectangleGeometry" ],
    [ "RotatingRayOfLightObject", "classRotatingRayOfLightObject.html", "classRotatingRayOfLightObject" ],
    [ "short_message_t", "structshort__message__t.html", "structshort__message__t" ],
    [ "Simulation", "classSimulation.html", "classSimulation" ],
    [ "slip_error_counter_s", "structslip__error__counter__s.html", "structslip__error__counter__s" ],
    [ "StaticLightObject", "classStaticLightObject.html", "classStaticLightObject" ],
    [ "time_reference_t", "structtime__reference__t.html", "structtime__reference__t" ]
];