var searchData=
[
  ['parallel_20with_20different_20configuration_20options_0',['Launch several runs in Parallel, with different configuration options',['../index.html#autotoc_md137',1,'']]],
  ['parameters_1',['Parameters',['../spogobot_8h.html#autotoc_md11',1,'Parameters'],['../spogobot_8h.html#autotoc_md23',1,'Parameters'],['../spogobot_8h.html#autotoc_md25',1,'Parameters'],['../spogobot_8h.html#autotoc_md27',1,'Parameters'],['../spogobot_8h.html#autotoc_md29',1,'Parameters'],['../spogobot_8h.html#autotoc_md31',1,'Parameters'],['../spogobot_8h.html#autotoc_md33',1,'Parameters'],['../spogobot_8h.html#autotoc_md35',1,'Parameters'],['../spogobot_8h.html#autotoc_md37',1,'Parameters'],['../spogobot_8h.html#autotoc_md39',1,'Parameters'],['../spogobot_8h.html#autotoc_md41',1,'Parameters'],['../spogobot_8h.html#autotoc_md43',1,'Parameters'],['../spogobot_8h.html#autotoc_md45',1,'Parameters'],['../spogobot_8h.html#autotoc_md47',1,'Parameters'],['../spogobot_8h.html#autotoc_md49',1,'Parameters'],['../spogobot_8h.html#autotoc_md51',1,'Parameters'],['../spogobot_8h.html#autotoc_md54',1,'Parameters'],['../spogobot_8h.html#autotoc_md56',1,'Parameters'],['../spogobot_8h.html#autotoc_md61',1,'Parameters'],['../spogobot_8h.html#autotoc_md64',1,'Parameters'],['../spogobot_8h.html#autotoc_md66',1,'Parameters'],['../spogobot_8h.html#autotoc_md69',1,'Parameters'],['../spogobot_8h.html#autotoc_md75',1,'Parameters'],['../spogobot_8h.html#autotoc_md77',1,'Parameters'],['../spogobot_8h.html#autotoc_md79',1,'Parameters'],['../spogobot_8h.html#autotoc_md81',1,'Parameters'],['../spogobot_8h.html#autotoc_md83',1,'Parameters'],['../spogobot_8h.html#autotoc_md85',1,'Parameters'],['../spogobot_8h.html#autotoc_md87',1,'Parameters'],['../spogobot_8h.html#autotoc_md90',1,'Parameters'],['../spogobot_8h.html#autotoc_md92',1,'Parameters'],['../spogobot_8h.html#autotoc_md94',1,'Parameters'],['../spogobot_8h.html#autotoc_md97',1,'Parameters'],['../spogobot_8h.html#autotoc_md100',1,'Parameters'],['../spogobot_8h.html#autotoc_md102',1,'Parameters'],['../spogobot_8h.html#autotoc_md104',1,'Parameters'],['../spogobot_8h.html#autotoc_md106',1,'Parameters'],['../spogobot_8h.html#autotoc_md108',1,'Parameters'],['../spogobot_8h.html#autotoc_md110',1,'Parameters'],['../spogobot_8h.html#autotoc_md112',1,'Parameters'],['../spogobot_8h.html#autotoc_md114',1,'Parameters'],['../spogobot_8h.html#autotoc_md116',1,'Parameters']]],
  ['parameters_2',['Data storage - retrieve simulation dataframes and configuration parameters',['../index.html#autotoc_md136',1,'']]],
  ['parameters_20of_20the_20simulator_3',['Command line parameters of the simulator',['../index.html#autotoc_md131',1,'']]],
  ['payload_20in_20a_20ir_20message_4',['Maximum size of a payload in a IR message',['../spogobot_8h.html#autotoc_md13',1,'']]],
  ['photosensor_20id_20definition_5',['Photosensor id definition',['../spogobot_8h.html#autotoc_md59',1,'']]],
  ['photosensors_20api_20functions_6',['Photosensors API Functions',['../spogobot_8h.html#autotoc_md60',1,'']]],
  ['photosensors_20api_20values_7',['Photosensors API Values',['../spogobot_8h.html#autotoc_md4',1,'Photosensors API Values'],['../spogobot_8h.html#autotoc_md58',1,'Photosensors API Values']]],
  ['pogobatch_20mode_20i_20get_20an_20sdl_20related_20error_8',['In headless/Pogobatch mode, I get an SDL-related error',['../index.html#autotoc_md133',1,'']]],
  ['pogobot_20pogosim_20project_9',['Simple way to create a new pogobot/pogosim project',['../index.html#autotoc_md126',1,'']]],
  ['pogobots_10',['Compile a binary for the real Pogobots',['../index.html#autotoc_md128',1,'']]],
  ['pogosim_11',['Pogosim &lt;img src=&quot;https://github.com/Adacoma/pogosim/actions/workflows/ci.yaml/badge.svg&quot; alt=&quot;Badge CI&quot; style=&quot;pointer-events: none;&quot; class=&quot;inline&quot;/&gt; &lt;img src=&quot;https://img.shields.io/badge/version-v0.10.10-blue&quot; alt=&quot;Version&quot; class=&quot;inline&quot;/&gt;',['../index.html',1,'']]],
  ['pogosim_20project_12',['Simple way to create a new pogobot/pogosim project',['../index.html#autotoc_md126',1,'']]],
  ['pose_20and_20states_20of_20the_20robots_20in_20python_13',['Access the pose and states of the robots in Python',['../index.html#autotoc_md134',1,'']]],
  ['power_20level_20values_3a_14',['IR power level values:',['../spogobot_8h.html#autotoc_md15',1,'']]],
  ['project_15',['Simple way to create a new pogobot/pogosim project',['../index.html#autotoc_md126',1,'']]],
  ['projects_16',['Compiling binaries for multi-categories projects',['../index.html#autotoc_md129',1,'']]],
  ['python_17',['Access the pose and states of the robots in Python',['../index.html#autotoc_md134',1,'']]]
];
