var searchData=
[
  ['range_20_3a_0',['Motor range :',['../spogobot_8h.html#autotoc_md73',1,'']]],
  ['real_20pogobots_1',['Compile a binary for the real Pogobots',['../index.html#autotoc_md128',1,'']]],
  ['recovers_20in_20one_20step_2',['Maximum number of word from IR recovers in one step',['../spogobot_8h.html#autotoc_md14',1,'']]],
  ['related_20error_3',['In headless/Pogobatch mode, I get an SDL-related error',['../index.html#autotoc_md133',1,'']]],
  ['return_4',['Return',['../spogobot_8h.html#autotoc_md12',1,'Return'],['../spogobot_8h.html#autotoc_md24',1,'Return'],['../spogobot_8h.html#autotoc_md26',1,'Return'],['../spogobot_8h.html#autotoc_md28',1,'Return'],['../spogobot_8h.html#autotoc_md30',1,'Return'],['../spogobot_8h.html#autotoc_md32',1,'Return'],['../spogobot_8h.html#autotoc_md34',1,'Return'],['../spogobot_8h.html#autotoc_md36',1,'Return'],['../spogobot_8h.html#autotoc_md38',1,'Return'],['../spogobot_8h.html#autotoc_md40',1,'Return'],['../spogobot_8h.html#autotoc_md42',1,'Return'],['../spogobot_8h.html#autotoc_md44',1,'Return'],['../spogobot_8h.html#autotoc_md46',1,'Return'],['../spogobot_8h.html#autotoc_md48',1,'Return'],['../spogobot_8h.html#autotoc_md50',1,'Return'],['../spogobot_8h.html#autotoc_md52',1,'Return'],['../spogobot_8h.html#autotoc_md55',1,'Return'],['../spogobot_8h.html#autotoc_md57',1,'Return'],['../spogobot_8h.html#autotoc_md62',1,'Return'],['../spogobot_8h.html#autotoc_md65',1,'Return'],['../spogobot_8h.html#autotoc_md67',1,'Return'],['../spogobot_8h.html#autotoc_md70',1,'Return'],['../spogobot_8h.html#autotoc_md76',1,'Return'],['../spogobot_8h.html#autotoc_md78',1,'Return'],['../spogobot_8h.html#autotoc_md80',1,'Return'],['../spogobot_8h.html#autotoc_md82',1,'Return'],['../spogobot_8h.html#autotoc_md84',1,'Return'],['../spogobot_8h.html#autotoc_md86',1,'Return'],['../spogobot_8h.html#autotoc_md88',1,'Return'],['../spogobot_8h.html#autotoc_md91',1,'Return'],['../spogobot_8h.html#autotoc_md93',1,'Return'],['../spogobot_8h.html#autotoc_md95',1,'Return'],['../spogobot_8h.html#autotoc_md98',1,'Return'],['../spogobot_8h.html#autotoc_md101',1,'Return'],['../spogobot_8h.html#autotoc_md103',1,'Return'],['../spogobot_8h.html#autotoc_md105',1,'Return'],['../spogobot_8h.html#autotoc_md107',1,'Return'],['../spogobot_8h.html#autotoc_md109',1,'Return'],['../spogobot_8h.html#autotoc_md111',1,'Return'],['../spogobot_8h.html#autotoc_md113',1,'Return'],['../spogobot_8h.html#autotoc_md115',1,'Return'],['../spogobot_8h.html#autotoc_md117',1,'Return'],['../spogobot_8h.html#autotoc_md118',1,'Return']]],
  ['rgb_20led_20api_5',['RGB LED API',['../spogobot_8h.html#autotoc_md3',1,'RGB LED API'],['../spogobot_8h.html#autotoc_md53',1,'RGB LED API']]],
  ['robots_20in_20python_6',['Access the pose and states of the robots in Python',['../index.html#autotoc_md134',1,'']]],
  ['runs_20in_20parallel_20with_20different_20configuration_20options_7',['Launch several runs in Parallel, with different configuration options',['../index.html#autotoc_md135',1,'']]]
];
