string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(TEST_DIR "${CMAKE_CURRENT_BINARY_DIR}/regression/flash-example-${nonce}")
file(MAKE_DIRECTORY "${TEST_DIR}")
foreach(case bootstrap_strict export import export_five import_two_from_five
        import_five_after_subset bootstrap bootstrap_import bootstrap_input_only)
    file(READ "${SOURCE_DIR}/examples/test_flash_state/conf/${case}.yaml" yaml)
    string(REPLACE "frames/" "${TEST_DIR}/" yaml "${yaml}")
    set(config "${TEST_DIR}/${case}.yaml")
    file(WRITE "${config}" "${yaml}")
    execute_process(COMMAND "${PROGRAM}" -c "${config}" -g -nr
        WORKING_DIRECTORY "${SOURCE_DIR}" RESULT_VARIABLE status
        OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
    if(case STREQUAL "bootstrap_strict")
        if(NOT "${status}" STREQUAL "2")
            message(FATAL_ERROR "Strict missing-file import returned ${status}: ${output}${error}")
        endif()
        string(FIND "${output}${error}" "Unable to open flash-state archive" found)
        if(found EQUAL -1 OR EXISTS "${TEST_DIR}/test_flash_state_bootstrap.pgflash")
            message(FATAL_ERROR "Wrong strict missing-file behavior: ${output}${error}")
        endif()
    elseif(NOT "${status}" STREQUAL "0")
        message(FATAL_ERROR "Flash case ${case} returned ${status}: ${output}${error}")
    endif()
endforeach()
# Input-only bootstrap creates a marker, not an indeterminate-flash snapshot.
file(SIZE "${TEST_DIR}/test_flash_state_empty_only.pgflash" size)
if(NOT size EQUAL 18)
    message(FATAL_ERROR "Input-only archive has ${size} bytes, expected 18")
endif()
