# Every case gets separate outputs. Check exact statuses so a crash or missing
# Windows DLL can never pass merely because the process failed.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(TEST_DIR "${CMAKE_CURRENT_BINARY_DIR}/regression/${CASE}-${nonce}")
file(MAKE_DIRECTORY "${TEST_DIR}")
set(CONFIG "${TEST_DIR}/simulation.yaml")
set(OUTPUT "${TEST_DIR}/simulation.feather")
set(mode 0)
set(boundary solid)
set(rate 1)
set(source_x 250)
set(peer_x 350)
set(radius 26.5)
set(range 200)
set(logging false)
set(extra "")
set(status 0)
set(diagnostic "")
if(CASE STREQUAL "communication_drop")
    set(mode 1)
    set(rate 0)
elseif(CASE MATCHES "^logging_")
    set(mode 2)
    set(logging true)
    if(CASE STREQUAL "logging_restricted")
        set(extra "data_logger_fields: [time, robot_category, robot_id, controller_steps]\ndata_logger_category: [robots]\n")
    endif()
elseif(CASE STREQUAL "periodic_neighbors_and_wrap" OR CASE STREQUAL "solid_distant_neighbors")
    set(source_x 5)
    set(peer_x 995)
    set(radius 1)
    set(range 20)
    set(mode 4)
    if(CASE STREQUAL "periodic_neighbors_and_wrap")
        set(mode 3)
        set(boundary periodic)
    endif()
elseif(CASE STREQUAL "schema_callback_failure" OR CASE STREQUAL "export_callback_failure")
    set(logging true)
    set(status 2)
    set(mode 6)
    set(diagnostic "regression schema failure")
    if(CASE STREQUAL "export_callback_failure")
        set(mode 7)
        set(diagnostic "regression export failure")
    endif()
endif()
set(yaml "seed: 1\narena_file: '${SOURCE_DIR}/arenas/square.csv'\narena_surface: 1000000\nboundary_condition: ${boundary}\ncommunication_ignore_occlusions: true\nenable_console_logging: false\nenable_data_logging: ${logging}\ndata_filename: '${OUTPUT}'\ndata_logger_flush_row_count: 3\nsimulation_time: 0.03\ntime_step: 0.001\nsave_data_period: 0.002\nsave_video_period: -1\n${extra}parameters: {regression_mode: ${mode}}\nobjects:\n")
# Emit complete mappings: yaml-cpp does not expand YAML merge keys.
foreach(category robots peers)
    set(x ${source_x})
    if(category STREQUAL "peers")
        set(x ${peer_x})
    endif()
    string(APPEND yaml "  ${category}:\n    type: pogobot\n    nb: 1\n    geometry: disk\n    radius: ${radius}\n    x: ${x}\n    y: 500\n    communication_radius: ${range}\n    temporal_noise_stddev: 0\n    linear_noise_stddev: 0\n    angular_noise_stddev: 0\n    msg_success_rate: {type: static, rate: ${rate}}\n")
endforeach()
if(CASE MATCHES "^startup_")
    set(status 2)
    if(CASE STREQUAL "startup_yaml")
        set(yaml "objects: [\n")
        set(status 1)
        set(diagnostic "Error reading YAML file")
    elseif(CASE STREQUAL "startup_missing_arena")
        string(REPLACE "${SOURCE_DIR}/arenas/square.csv" "${TEST_DIR}/missing.csv" yaml "${yaml}")
        set(diagnostic "Impossible to load file")
    elseif(CASE STREQUAL "startup_unknown_object")
        string(REPLACE "type: pogobot" "type: invalid-object" yaml "${yaml}")
        set(diagnostic "Unknown object type")
    elseif(CASE STREQUAL "startup_unknown_geometry")
        string(REPLACE "geometry: disk" "geometry: invalid-geometry" yaml "${yaml}")
        set(diagnostic "Unknown geometry type")
    elseif(CASE STREQUAL "startup_empty_output")
        string(REPLACE "enable_data_logging: false" "enable_data_logging: true" yaml "${yaml}")
        string(REPLACE "data_filename: '${OUTPUT}'" "data_filename: ''" yaml "${yaml}")
        set(diagnostic "data_filename' is empty")
    elseif(CASE STREQUAL "startup_output_directory")
        string(REPLACE "enable_data_logging: false" "enable_data_logging: true" yaml "${yaml}")
        string(REPLACE "data_filename: '${OUTPUT}'" "data_filename: '${TEST_DIR}'" yaml "${yaml}")
        set(diagnostic "Failed to open file for writing")
    elseif(CASE STREQUAL "startup_empty_console")
        string(APPEND yaml "enable_console_logging: true\nconsole_filename: ''\n")
        # Avoid duplicate top-level keys: yaml-cpp retains the first lookup.
        string(REPLACE "enable_console_logging: false\n" "" yaml "${yaml}")
        set(diagnostic "console_filename' is empty")
    elseif(CASE STREQUAL "startup_unknown_magnetometer")
        string(APPEND yaml "magnetometer: {source: invalid, angle_unit: degrees}\n")
        set(diagnostic "Unknown magnetometer source")
    else()
        message(FATAL_ERROR "Unknown startup case ${CASE}")
    endif()
endif()
file(WRITE "${CONFIG}" "${yaml}")
execute_process(COMMAND "${PROGRAM}" -c "${CONFIG}" -g -nr -s 17
    WORKING_DIRECTORY "${SOURCE_DIR}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 20)
if(NOT "${result}" STREQUAL "${status}")
    message(FATAL_ERROR "Expected exit ${status}, got ${result}: ${output}${error}")
endif()
string(FIND "${output}${error}" "${diagnostic}" found)
if(found EQUAL -1)
    message(FATAL_ERROR "Missing '${diagnostic}': ${output}${error}")
endif()
if(CASE MATCHES "^logging_")
    set(verify verify_all)
    if(CASE STREQUAL "logging_restricted")
        set(verify verify_restricted)
    endif()
    execute_process(COMMAND "${VERIFIER}" "${verify}" "${OUTPUT}" "${SOURCE_DIR}"
        RESULT_VARIABLE verified OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 20)
    if(NOT "${verified}" STREQUAL "0")
        message(FATAL_ERROR "Feather verification failed: ${output}${error}")
    endif()
elseif(NOT logging AND EXISTS "${OUTPUT}")
    message(FATAL_ERROR "Disabled data logging created a file")
endif()
